import { NAME_OR_PASSWORD_IS_REQUIRED, USER_ALREADY_EXISTS, USER_NOT_EXISTS, PASSWORD_IS_INCORRECT, UNAUTHORIZED } from './error-types';

export default { NAME_OR_PASSWORD_IS_REQUIRED, USER_ALREADY_EXISTS, USER_NOT_EXISTS, PASSWORD_IS_INCORRECT, UNAUTHORIZED };